"""Follow-up chat orchestration (PLAN_PART_5 §1).

Holds the in-process :class:`ChatStreamManager` (the chat analogue of the workflow
``event_bus``): the assistant reply is generated by a background task that pushes
token deltas into a per-message buffer, while the SSE endpoint replays the buffer
and tails live updates — giving refresh/reconnect resumability via ``sinceSeq``.

A turn is grounded by :mod:`app.retrieval.pack`: report markdown + a BM25-ranked
source pack + a sliding window of history. After streaming, ``[i]`` markers are
mapped back to source URLs for the UI citations row.
"""

from __future__ import annotations

import asyncio
import contextlib
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, Field

from app.exceptions import ChatMessageNotFound, ChatNoReport
from app.logging_config import get_logger
from app.models.chat import (
    ChatAccepted,
    ChatError,
    ChatListResponse,
    ChatMessageOut,
    ChatRole,
    ChatStatus,
    ChatSuggestionsOut,
    Citation,
)
from app.repositories import chat_repo, report_repo, session_repo, workflow_repo
from app.retrieval import pack
from app.services import session_service
from app.workflow.tools.llm import StreamUsage

if TYPE_CHECKING:
    from motor.motor_asyncio import AsyncIOMotorDatabase

    from app.models.report import ReportOut
    from app.models.session import SessionOut
    from app.workflow.deps import WorkflowDeps

log = get_logger("chat.service")

# Sliding window of prior turns fed into the prompt (PLAN §1.3.4).
_HISTORY_WINDOW = 10
# How many raw sources to pack into a turn.
_SOURCE_TOP_K = 6
# Fallback starter prompts if LLM suggestion generation is unavailable.
_FALLBACK_SUGGESTIONS = [
    "What's their biggest growth signal right now?",
    "Who should I reach out to first, and why?",
    "What objections should I be ready for?",
]


# --- in-process stream manager -------------------------------------------------


@dataclass
class _StreamState:
    """Live buffer + subscribers for one streaming assistant message."""

    deltas: list[tuple[int, str]] = field(default_factory=list)
    subscribers: set[asyncio.Queue[dict[str, Any]]] = field(default_factory=set)
    done: bool = False
    final: dict[str, Any] | None = None
    task: asyncio.Task[None] | None = None
    _seq: int = 0


class ChatStreamManager:
    """Process-wide registry of in-flight chat replies (one per message id)."""

    def __init__(self) -> None:
        self._streams: dict[str, _StreamState] = {}

    def open(self, message_id: str) -> _StreamState:
        state = _StreamState()
        self._streams[message_id] = state
        return state

    def get(self, message_id: str) -> _StreamState | None:
        return self._streams.get(message_id)

    def attach_task(self, message_id: str, task: asyncio.Task[None]) -> None:
        state = self._streams.get(message_id)
        if state is not None:
            state.task = task

    def publish_delta(self, message_id: str, text: str) -> None:
        state = self._streams.get(message_id)
        if state is None:
            return
        state._seq += 1
        seq = state._seq
        state.deltas.append((seq, text))
        frame = {"type": "delta", "seq": seq, "text": text}
        for queue in list(state.subscribers):
            with contextlib.suppress(asyncio.QueueFull):
                queue.put_nowait(frame)

    def finish(
        self,
        message_id: str,
        *,
        status: ChatStatus,
        citations: list[Citation],
        error: ChatError | None,
    ) -> None:
        state = self._streams.get(message_id)
        if state is None:
            return
        state.done = True
        state.final = {
            "type": "done",
            "messageId": message_id,
            "status": status.value,
            "citations": [c.model_dump(by_alias=True) for c in citations],
            "error": error.model_dump(by_alias=True) if error else None,
        }
        for queue in list(state.subscribers):
            with contextlib.suppress(asyncio.QueueFull):
                queue.put_nowait(state.final)

    def subscribe(self, message_id: str) -> asyncio.Queue[dict[str, Any]]:
        state = self._streams.setdefault(message_id, _StreamState())
        queue: asyncio.Queue[dict[str, Any]] = asyncio.Queue(maxsize=1024)
        state.subscribers.add(queue)
        return queue

    def unsubscribe(
        self, message_id: str, queue: asyncio.Queue[dict[str, Any]]
    ) -> None:
        state = self._streams.get(message_id)
        if state is not None:
            state.subscribers.discard(queue)

    def discard(self, message_id: str) -> None:
        """Drop a stream's buffer (after retry deletes its message)."""
        self._streams.pop(message_id, None)

    async def shutdown(self) -> None:
        """Cancel any in-flight generation tasks (graceful shutdown)."""
        for state in list(self._streams.values()):
            if state.task is not None and not state.task.done():
                state.task.cancel()
                with contextlib.suppress(asyncio.CancelledError, Exception):
                    await state.task


stream_manager = ChatStreamManager()


# --- suggestions schema --------------------------------------------------------


class _Suggestions(BaseModel):
    """LLM output for the three starter chips."""

    suggestions: list[str] = Field(default_factory=list)


# --- generation ----------------------------------------------------------------


def _prior_citation_urls(history: list[ChatMessageOut]) -> set[str]:
    """URLs cited by the last two assistant turns (carried into the next pack)."""
    assistants = [m for m in history if m.role is ChatRole.ASSISTANT][-2:]
    urls: set[str] = set()
    for msg in assistants:
        urls.update(c.url for c in msg.citations)
    return urls


async def _generate(
    db: AsyncIOMotorDatabase,
    deps: WorkflowDeps,
    session: SessionOut,
    report: ReportOut,
    *,
    message_id: str,
    question: str,
    history: list[ChatMessageOut],
) -> None:
    """Stream one grounded assistant reply, persisting deltas + final citations."""
    usage = StreamUsage()
    chunks: list[str] = []
    try:
        sources = await workflow_repo.get_latest_raw_sources(db, session.id)
        selected = pack.select_sources(
            sources,
            question=question,
            objective=session.objective,
            prior_citation_urls=_prior_citation_urls(history),
            top_k=_SOURCE_TOP_K,
        )
        messages = pack.build_messages(
            report_md=pack.report_to_markdown(report),
            selected=selected,
            history=history,
            question=question,
        )
        model = deps.settings.model_for_node("chat")
        async for delta in deps.llm.stream(messages, model=model, usage=usage):
            chunks.append(delta)
            stream_manager.publish_delta(message_id, delta)

        text = "".join(chunks)
        citations = pack.parse_citations(text, selected)
        await chat_repo.finalize_message(
            db,
            message_id,
            content=text,
            citations=citations,
            model=usage.model,
            tokens_in=usage.tokens_in,
            tokens_out=usage.tokens_out,
            cost_usd=usage.cost_usd,
        )
        stream_manager.finish(
            message_id,
            status=ChatStatus.COMPLETE,
            citations=citations,
            error=None,
        )
        log.info(
            "chat_reply_complete",
            session_id=session.id,
            message_id=message_id,
            citations=len(citations),
            tokens_out=usage.tokens_out,
        )
    except asyncio.CancelledError:  # graceful shutdown mid-stream
        error = ChatError(code="chat_interrupted", message="Generation was interrupted.")
        await chat_repo.fail_message(db, message_id, error=error)
        stream_manager.finish(
            message_id, status=ChatStatus.FAILED, citations=[], error=error
        )
        raise
    except Exception as exc:
        log.error("chat_reply_failed", message_id=message_id, error=str(exc))
        error = ChatError(code="chat_provider_error", message=str(exc)[:500])
        await chat_repo.fail_message(db, message_id, error=error)
        stream_manager.finish(
            message_id, status=ChatStatus.FAILED, citations=[], error=error
        )


async def _launch(
    db: AsyncIOMotorDatabase,
    deps: WorkflowDeps,
    session: SessionOut,
    report: ReportOut,
    *,
    question: str,
    history: list[ChatMessageOut],
) -> str:
    """Create the assistant placeholder and start its generation task."""
    message_id = await chat_repo.create_message(
        db,
        session.id,
        role=ChatRole.ASSISTANT,
        content="",
        status=ChatStatus.STREAMING,
    )
    stream_manager.open(message_id)
    task = asyncio.create_task(
        _generate(
            db,
            deps,
            session,
            report,
            message_id=message_id,
            question=question,
            history=history,
        )
    )
    stream_manager.attach_task(message_id, task)
    return message_id


# --- public service API --------------------------------------------------------


async def _require_report(
    db: AsyncIOMotorDatabase, session_id: str
) -> tuple[SessionOut, ReportOut]:
    session = await session_service.get_session(db, session_id)  # 404 if absent
    report = await report_repo.get_by_session(db, session_id)
    if report is None:
        raise ChatNoReport(session_id)
    return session, report


async def post_message(
    db: AsyncIOMotorDatabase,
    deps: WorkflowDeps,
    session_id: str,
    content: str,
) -> ChatAccepted:
    """Persist a user message and start streaming the grounded assistant reply."""
    session, report = await _require_report(db, session_id)
    history = await chat_repo.recent_history(db, session_id, limit=_HISTORY_WINDOW)
    await chat_repo.create_message(
        db,
        session_id,
        role=ChatRole.USER,
        content=content,
        status=ChatStatus.COMPLETE,
    )
    message_id = await _launch(
        db, deps, session, report, question=content, history=history
    )
    return ChatAccepted(message_id=message_id)


async def retry_last(
    db: AsyncIOMotorDatabase, deps: WorkflowDeps, session_id: str
) -> ChatAccepted:
    """Regenerate the last assistant reply from the same user question (PLAN §1.4)."""
    session, report = await _require_report(db, session_id)
    msgs = await chat_repo.list_messages(db, session_id, limit=1000, skip=0)
    last_user_idx = next(
        (i for i in range(len(msgs) - 1, -1, -1) if msgs[i].role is ChatRole.USER),
        None,
    )
    if last_user_idx is None:
        raise ChatMessageNotFound("(no user message to retry)")
    question = msgs[last_user_idx].content
    # Drop the trailing assistant reply(ies) for that question.
    for msg in msgs[last_user_idx + 1 :]:
        if msg.role is ChatRole.ASSISTANT:
            await chat_repo.delete_message(db, msg.id)
            stream_manager.discard(msg.id)
    history = msgs[:last_user_idx][-_HISTORY_WINDOW:]
    message_id = await _launch(
        db, deps, session, report, question=question, history=history
    )
    return ChatAccepted(message_id=message_id)


async def get_message(
    db: AsyncIOMotorDatabase, session_id: str, message_id: str
) -> ChatMessageOut:
    """Fetch one chat message scoped to its session (404 if absent)."""
    await session_service.get_session(db, session_id)
    msg = await chat_repo.get_message(db, session_id, message_id)
    if msg is None:
        raise ChatMessageNotFound(message_id)
    return msg


async def list_history(
    db: AsyncIOMotorDatabase, session_id: str, *, limit: int, skip: int
) -> ChatListResponse:
    """Return paginated visible chat history (oldest-first)."""
    await session_service.get_session(db, session_id)
    items = await chat_repo.list_messages(db, session_id, limit=limit, skip=skip)
    total = await chat_repo.count_messages(db, session_id)
    return ChatListResponse(items=items, total=total)


async def get_suggestions(
    db: AsyncIOMotorDatabase, deps: WorkflowDeps, session_id: str
) -> ChatSuggestionsOut:
    """Return three starter prompts, generating + caching them on first call."""
    _session, report = await _require_report(db, session_id)
    cached = await session_repo.get_chat_suggestions(db, session_id)
    if cached:
        return ChatSuggestionsOut(suggestions=cached[:3])

    suggestions = await _generate_suggestions(deps, report)
    await session_repo.set_chat_suggestions(db, session_id, suggestions)
    return ChatSuggestionsOut(suggestions=suggestions)


async def _generate_suggestions(
    deps: WorkflowDeps, report: ReportOut
) -> list[str]:
    """LLM-generate three crisp starter questions; fall back to defaults on error."""
    try:
        system = (
            "You generate exactly three short, punchy follow-up questions a "
            "salesperson would ask about a company after reading a research brief. "
            "Each under 12 words, action-oriented, no numbering."
        )
        user = (
            f"Company: {report.company_overview[:600]}\n"
            "Return three starter questions."
        )
        result = await deps.llm.complete(
            system,
            user,
            response_model=_Suggestions,
            model=deps.settings.model_for_node("chat"),
            temperature=0.5,
            max_tokens=200,
        )
        cleaned = [s.strip() for s in result.suggestions if s.strip()][:3]
        return cleaned or _FALLBACK_SUGGESTIONS
    except Exception as exc:
        log.warning("chat_suggestions_fallback", error=str(exc))
        return _FALLBACK_SUGGESTIONS
